name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ windows-latest, macos-latest, ubuntu-latest ]

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Setup .NET 6
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 6.0.x
    - name: Setup .NET 8
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test --configuration Release --no-build
    - name: Validate generated css files
      run: |
        test -s Samples/AspNetCore.SassCompiler.BlazorSample/Components/Pages/Counter.razor.css
        test -s Samples/AspNetCore.SassCompiler.BlazorSample/obj/Release/net8.0/scopedcss/Components/Pages/Counter.razor.rz.scp.css
        test -s Samples/AspNetCore.SassCompiler.BlazorWasmSample/Pages/Counter.razor.css
        test -s Samples/AspNetCore.SassCompiler.BlazorWasmSample/obj/Release/net8.0/scopedcss/Pages/Counter.razor.rz.scp.css
        test -s Samples/AspNetCore.SassCompiler.RazorClassLibrary/Component1.razor.css
        test -s Samples/AspNetCore.SassCompiler.RazorClassLibrary/obj/Release/net6.0/scopedcss/Component1.razor.rz.scp.css
        test -s Samples/AspNetCore.SassCompiler.Sample/wwwroot/css/site_sass.css
        test -s Samples/AspNetCore.SassCompiler.Sample/wwwroot/lib/css/lib.min.css
